name: CI Test

on:
  pull_request:
    paths-ignore:
      - '*.commits'
      - '*.markdown'
      - '**/*.markdown'

env:
  LC_ALL: en_US.UTF-8

jobs:
  TestCreateProjects:
    name: Test Create Projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        shell: bash
        env:
          GITHUB_CI: "true"
          DOCKER_NETWORK: "host"
        run: |
          export LOCALDEV_REPO=${GITHUB_WORKSPACE}
          ./tests/integration/test-create-projects.sh
  TestDemoWorkspace:
    name: Test Demo Workspace
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check Source Formatting
        shell: bash
        run: |
          pip3 install black
          find . -name '*.py' -print | xargs black --check
      - name: Build
        shell: bash
        env:
          GITHUB_CI: "true"
          DOCKER_NETWORK: "host"
        run: |
          export LOCALDEV_REPO=${GITHUB_WORKSPACE}
          ./tests/functional/test-demo-workspace.sh